# Generated by Django 4.1 on 2022-10-02 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50, verbose_name='Descripción')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo de clasificación')),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo original')),
                ('year', models.PositiveIntegerField(verbose_name='Año de publicación')),
                ('duration', models.PositiveIntegerField(verbose_name='Duración en minutos')),
                ('ISAN', models.CharField(max_length=96, verbose_name='ISAN')),
                ('image_thumbnail', models.ImageField(blank=True, null=True, upload_to='films/', verbose_name='Miniatura')),
                ('film_url', models.URLField(max_length=150, verbose_name='Url de la película')),
                ('actor', models.CharField(max_length=250, verbose_name='Actores')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.category', verbose_name='Categoría')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.classification', verbose_name='Clasificación')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'películas',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=30, verbose_name='Idioma')),
                ('type', models.CharField(max_length=50, verbose_name='Tipo de idioma')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo original')),
                ('season', models.PositiveIntegerField(default=0, verbose_name='Temporada')),
                ('fimls', models.ManyToManyField(related_name='fimls_serie', to='films.film', verbose_name='Peliculas')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='film',
            name='language',
            field=models.ManyToManyField(related_name='film_language', to='films.language', verbose_name='Idiomas'),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISAN', models.CharField(max_length=96, verbose_name='ISAN')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo original')),
                ('volume', models.PositiveIntegerField(default=0, verbose_name='Volumen')),
                ('fimls', models.ManyToManyField(related_name='fimls_collection', to='films.film', verbose_name='Peliculas')),
            ],
            options={
                'verbose_name': 'Colección',
                'verbose_name_plural': 'Colecciones',
                'ordering': ['title'],
            },
        ),
    ]
