# Generated by Django 4.1 on 2022-10-02 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='film_url',
        ),
        migrations.AddField(
            model_name='film',
            name='film',
            field=models.FileField(default='films/default.mp4', upload_to='films/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='Película'),
        ),
        migrations.AddField(
            model_name='film',
            name='review_short',
            field=models.TextField(blank=True, null=True, verbose_name='Argumento corto'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='films/img/', verbose_name='Foto Miniatura'),
        ),
    ]
