# Generated by Django 4.1 on 2022-11-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_rename_film_film_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='image_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='series/img/', verbose_name='Foto Miniatura'),
        ),
        migrations.AddField(
            model_name='serie',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
