# Generated by Django 4.1 on 2022-11-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_serie_image_thumbnail_serie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='main_character',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Prsonaje principal'),
        ),
    ]
