# Generated by Django 4.1 on 2022-10-17 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='profile_images', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'bpm', 'jpeg', 'jpe'])]),
        ),
    ]
