# Generated by Django 4.1 on 2022-11-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount_transactions',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de transacciones'),
        ),
    ]
