# Generated by Django 4.1 on 2022-11-01 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0002_remove_film_film_url_film_film_film_review_short_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de transacción')),
                ('type_transaction', models.CharField(choices=[('C', 'Comprar'), ('A', 'Alquilar')], max_length=1, verbose_name='Tipo de transacción')),
                ('start_time_rent', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha inicio del alquiler')),
                ('end_time_rent', models.DateField(blank=True, null=True, verbose_name='Fecha fin del alquiler')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente quien hizo la transacción')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film', verbose_name='Película')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
    ]
