# Generated by Django 4.1 on 2022-10-14 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('P', 'Pregunta'), ('Q', 'Queja'), ('R', 'Reclamo')], max_length=1, verbose_name='Tipo de solicitud')),
                ('request_detail', models.TextField(verbose_name='Detalle de la solicitud')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente que radica el PQR')),
            ],
            options={
                'verbose_name': 'PQR',
                'verbose_name_plural': 'PQRs',
            },
        ),
    ]
