# Generated by Django 4.1 on 2022-10-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pqr',
            name='request_type',
            field=models.CharField(choices=[('', 'Seleccione el tipo de solicitud'), ('P', 'Pregunta'), ('Q', 'Queja'), ('R', 'Reclamo')], max_length=1, verbose_name='Tipo de solicitud'),
        ),
    ]
