# Generated by Django 4.1 on 2022-11-01 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0002_alter_pqr_request_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pqr',
            options={'verbose_name': 'Pregunta, Queja y Reclamo', 'verbose_name_plural': 'Preguntas, Quejas y Reclamos'},
        ),
    ]
